name:                minehask
version:             0.1.0.0
license:             BSD3
author:              "Victor Nazzaro"
maintainer:          "nazzav923@gmail.com"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/minehask#readme>

dependencies:
- base >= 4.7 && < 5
- MonadRandom
- monads-fd
- split
- transformers

library:
  source-dirs: src

executables:
  minehask-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - minehask

tests:
  minehask-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - minehask
